### ISSUE TITLE
npm WARN install:zmq@2.15.1 Exit status 1

### ISSUE THREAD

**Issue by heuels** [briskhome/briskhome#17]
При запуске `node-gyp rebuild` в консоли отображаются приведенные ниже сообщения об ошибках. Необходимо идентифицировать проблемный модуль, чьей зависимостью является **zmq** и устранить проблему.
```console

heuels:briskhome heuels$ npm install bunyan-mongodb-stream --save

> kerberos@0.0.19 install /opt/briskhome/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/kerberos.node

> zmq@2.14.0 install /opt/briskhome/node_modules/mosca/node_modules/zmq
> node-gyp rebuild

/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config libzmq --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/heuels/.nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/Users/heuels/.nvm/versions/node/v5.2.0/bin/node" "/Users/heuels/.nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/briskhome/node_modules/mosca/node_modules/zmq
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm WARN install:zmq@2.14.0 zmq@2.14.0 install: `node-gyp rebuild`
npm WARN install:zmq@2.14.0 Exit status 1

> zmq@2.15.1 install /opt/briskhome/node_modules/zmq
> node-gyp rebuild

/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config libzmq --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/heuels/.nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/Users/heuels/.nvm/versions/node/v5.2.0/bin/node" "/Users/heuels/.nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/briskhome/node_modules/zmq
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm WARN install:zmq@2.15.1 zmq@2.15.1 install: `node-gyp rebuild`
npm WARN install:zmq@2.15.1 Exit status 1
@briskhome/core@0.3.0 /opt/briskhome
├── bunyan-mongodb-stream@0.0.3 
├── config-node@1.2.2  extraneous (git://github.com/heuels/config-node.git#5a9f095c4ebb5473b039965d22bab5d624229302)
├── hap-nodejs@0.3.2  extraneous
├── kerberos@0.0.19 
├── mock-dgram@0.1.2 
├── nconf@0.8.4 
└── passport-restify@1.0.1 
```

----------------------------------------
- Bitbucket: https://bitbucket.org/briskhome/briskhome-core/issue/18

**Comment by heuels** [comment]
This issue will be kept open until **v0.3.0-alpha** is released which will feature npm shrinkwrap.

**Comment by heuels** [comment]
**zmq@2.14.0** is an optional dependency of **ascoltatori**, which in turn is a dependency of **mosca**.

**Comment by heuels** [comment]
**Solution**: setting the installation scripts to invole `--no-optional` flag, which will, unsurprisingly, do what is says: optional dependencies will not be installed.
