### ISSUE TITLE
Automate testing of core components

### ISSUE THREAD

**Issue by heuels** [briskhome/briskhome#27]
As of right now tests for each core module are run separately. A universal test file should be added that will automatically compile a list of all testable components in `lib` directory and run them one by one.

Here is a WIP snippet:
```javascript
/* global after, afterEach, before, beforeEach, describe, it */
/* eslint import/no-dynamic-require: [0]                                                          */
/* eslint import/no-extraneous-dependencies: ["error", {"devDependencies": true}] */
/* eslint global-require: [0] */
/* eslint func-names: [0] */
/* eslint prefer-arrow-callback: [0] */

/**
 * @briskhome </specs/briskhome.spec.js>
 *
 * Test suites for BRISKHOME.
 *
 * @author  Egor Zaitsev <ezaitsev@briskhome.com>
 */

'use strict';

const fs = require('fs');
const path = require('path');

describe('BRISKHOME', function () {
  it('should prepare a list of installed components', function () {
    function getDirectories(srcpath) {
      return fs.readdirSync(srcpath)
        .filter(file => fs.statSync(path.join(srcpath, file)).isDirectory());
    }

    const components = getDirectories('../lib');
    for (let i = 0; i < components.length; i += 1) {
      const subdirectories = getDirectories(path.join('../lib', components[i]));
      if (subdirectories.indexOf('specs') > -1) {
        describe(`${components[i]} component`, function () {
          require(path.join('../lib', components[i], 'specs', 'index.spec.js'));
        });
      }
    }
  });
});
```

Note that **it is not a complete solution**: 
- The first test case *"should prepare a list of installed components"* should assert list is not **null**.
- A second test case *"all components should have tests"* need to be addded that compares `components.length` and a number of components that have tests available.

**Comment by heuels** [comment]
Also, all **briskhome-core** codebase must be linted with **eslint**. Note that separate config file should be used for linting `*.spec.js` files or files in `spec` directories.

**Comment by heuels** [comment]
The following error occurs when trying to run the tests consecutively:
```
/opt/briskhome/node_modules/mongoose/lib/index.js:346
      throw new mongoose.Error.OverwriteModelError(name);
      ^
OverwriteModelError: Cannot overwrite `core:device` model once compiled.
    at Mongoose.model (/opt/briskhome/node_modules/mongoose/lib/index.js:346:13)
    at module.exports (/opt/briskhome/lib/core.db/models/device.model.js:35:13)
    at Object.<anonymous> (/opt/briskhome/lib/onewire/specs/index.spec.js:18:63)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at /Users/heuels/.nvm/versions/node/v5.2.0/lib/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/heuels/.nvm/versions/node/v5.2.0/lib/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/Users/heuels/.nvm/versions/node/v5.2.0/lib/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/Users/heuels/.nvm/versions/node/v5.2.0/lib/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
```

Solution (found [here](http://stackoverflow.com/a/38143030/975314)):
```javascript
let users
try {
    users = mongoose.model('users')
} catch (error) {
    users = mongoose.model('users', <UsersSchema...>)
}
```
