### ISSUE TITLE
Custom resources not picked up by core.loader component

### ISSUE THREAD

**Issue by heuels** [briskhome/briskhome#35]
Not just database schemas, but also API routes and configuration files.  

So, after commit 4c5d0fd (see #15) components are discovered and loaded automatically. But we forgot about picking up additional component files like database schemas, configuration files and API routes – they **are not** loaded at all.

**What needs to be done**:

1. Add component auto discovery support to **core.loader**.
2. Remove `.forEach` loop from **core.db** schema loading algorythm.

See attached error log (irrelevant statements not included).

```console
heuels-mac:briskhome heuels$ NODE_ENV=briskhome ./briskhome.js | bunyan
 
[2017-03-12T20:11:53.242Z]  INIT: briskhome/25426
Moment Timezone 0.3.1 was already loaded with data from 2015a
<...>
Initializing core.db component
<...>
TypeError: require(...) is not a function
    at models.forEach (/opt/briskhome/lib/core.db/index.js:31:28)
    at Array.forEach (native)
    at NativeConnection.db.connection.once (/opt/briskhome/lib/core.db/index.js:29:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at NativeConnection.emit (events.js:188:7)
    at open (/opt/briskhome/node_modules/mongoose/lib/connection.js:489:10)
    at /opt/briskhome/node_modules/mongoose/lib/connection.js:495:7
    at /opt/briskhome/node_modules/mongodb/lib/db.js:1417:5
    at handleCallback (/opt/briskhome/node_modules/mongodb/lib/utils.js:96:12)
    at _callback (/opt/briskhome/node_modules/mongodb/lib/db.js:1334:5)
    at /opt/briskhome/node_modules/mongodb/lib/db.js:1377:7
    at /opt/briskhome/node_modules/mongodb-core/lib/topologies/server.js:1052:5
    at finish (/opt/briskhome/node_modules/mongodb-core/lib/auth/scram.js:158:18)
    at handleEnd (/opt/briskhome/node_modules/mongodb-core/lib/auth/scram.js:171:9)
    at /opt/briskhome/node_modules/mongodb-core/lib/auth/scram.js:265:19
    at /opt/briskhome/node_modules/mongodb-core/lib/topologies/server.js:778:13
    at Callbacks.emit (/opt/briskhome/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at Connection.messageHandler (/opt/briskhome/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket.<anonymous> (/opt/briskhome/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
[2017-03-12T20:11:55.642Z]  INFO: briskhome/25426 on heuels-mac.local: Инициализация планировщика задач
[2017-03-12T20:11:55.651Z]  INFO: briskhome/25426 on heuels-mac.local: Инициализация модуля коротких сообщений
[2017-03-12T20:11:55.671Z]  INFO: briskhome/25426 on heuels-mac.local: Initializing core.bus component
[2017-03-12T20:11:55.676Z]  INFO: briskhome/25426 on heuels-mac.local: Initializing core.ldap component
<...>
 { MongooseError: Schema hasn't been registered for model "irrigation:circuit".
Use mongoose.model(name, schema)
    at Mongoose.model (/opt/briskhome/node_modules/mongoose/lib/index.js:335:13)
    at Object.setup (/opt/briskhome-irrigation/index.js:30:22)
    at startPlugins (/opt/briskhome/node_modules/architect/architect.js:470:24)
    at startPlugins (/opt/briskhome/node_modules/architect/architect.js:479:21)
    at register (/opt/briskhome/node_modules/architect/architect.js:510:13)
    at module.exports.<anonymous> (/opt/briskhome/lib/core.planner/index.js:50:5)
    at emitNone (events.js:86:13)
    at module.exports.emit (events.js:188:7)
    at /opt/briskhome/node_modules/agenda/lib/agenda.js:113:42
    at handleCallback (/opt/briskhome/node_modules/agenda/node_modules/mongodb/lib/utils.js:95:12)
    at /opt/briskhome/node_modules/agenda/node_modules/mongodb/lib/db.js:253:5
    at /opt/briskhome/node_modules/agenda/node_modules/mongodb-core/lib/topologies/server.js:795:13
    at Callbacks.emit (/opt/briskhome/node_modules/agenda/node_modules/mongodb-core/lib/topologies/server.js:94:3)
    at Connection.messageHandler (/opt/briskhome/node_modules/agenda/node_modules/mongodb-core/lib/topologies/server.js:235:23)
    at Socket.<anonymous> (/opt/briskhome/node_modules/agenda/node_modules/mongodb-core/lib/connection/connection.js:259:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:554:20)
  message: 'Schema hasn\'t been registered for model "irrigation:circuit".\nUse mongoose.model(name, schema)',
  name: 'MissingSchemaError',
  plugin: 
   { packagePath: '/opt/briskhome-irrigation',
     consumes: [ 'log', 'db', 'config', 'bus', 'planner' ],
     provides: [ 'irrigation' ],
     setup: [Function: setup] } }

/opt/briskhome/node_modules/agenda/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                  ^
MongooseError: Schema hasn't been registered for model "irrigation:circuit".
Use mongoose.model(name, schema)
    at Mongoose.model (/opt/briskhome/node_modules/mongoose/lib/index.js:335:13)
    at Object.setup (/opt/briskhome-irrigation/index.js:30:22)
    at startPlugins (/opt/briskhome/node_modules/architect/architect.js:470:24)
    at startPlugins (/opt/briskhome/node_modules/architect/architect.js:479:21)
    at register (/opt/briskhome/node_modules/architect/architect.js:510:13)
    at module.exports.<anonymous> (/opt/briskhome/lib/core.planner/index.js:50:5)
    at emitNone (events.js:86:13)
    at module.exports.emit (events.js:188:7)
    at /opt/briskhome/node_modules/agenda/lib/agenda.js:113:42
    at handleCallback (/opt/briskhome/node_modules/agenda/node_modules/mongodb/lib/utils.js:95:12)
    at /opt/briskhome/node_modules/agenda/node_modules/mongodb/lib/db.js:253:5
    at /opt/briskhome/node_modules/agenda/node_modules/mongodb-core/lib/topologies/server.js:795:13
    at Callbacks.emit (/opt/briskhome/node_modules/agenda/node_modules/mongodb-core/lib/topologies/server.js:94:3)
    at Connection.messageHandler (/opt/briskhome/node_modules/agenda/node_modules/mongodb-core/lib/topologies/server.js:235:23)
    at Socket.<anonymous> (/opt/briskhome/node_modules/agenda/node_modules/mongodb-core/lib/connection/connection.js:259:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:554:20)
```

**Comment by heuels** [comment]
Commit 010c600 implements a common interface to loading shared resources. Component `core.loader` is now marked as deprecated and will soon be removed.
