### ISSUE TITLE
SyntaxError: 'super' keyword unexpected here

### ISSUE THREAD

**Issue by heuels** [briskhome/briskhome#67]
This is what appears on attempting to run **Briskhome** via `node lib/core.js`:
```

   ██████╗ ██████╗ ██╗███████╗██╗  ██╗██╗  ██╗ ██████╗ ███╗   ███╗███████╗
   ██╔══██╗██╔══██╗██║██╔════╝██║ ██╔╝██║  ██║██╔═══██╗████╗ ████║██╔════╝
   ██████╔╝██████╔╝██║███████╗█████╔╝ ███████║██║   ██║██╔████╔██║█████╗
   ██╔══██╗██╔══██╗██║╚════██║██╔═██╗ ██╔══██║██║   ██║██║╚██╔╝██║██╔══╝
   ██████╔╝██║  ██║██║███████║██║  ██╗██║  ██║╚██████╔╝██║ ╚═╝ ██║███████╗
   ╚═════╝ ╚═╝  ╚═╝╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝

07:37:33.523Z  INFO briskhome/core: Initializing Briskhome v0.3.0
SyntaxError: 'super' keyword unexpected here07:37:34.020Z FATAL briskhome/core: SyntaxError: 'super' keyword unexpected here
✨  Done in 0.72s.```

**Comment by heuels** [comment]
Okay, this is a caused by side effects of switching branches:
```
/opt/briskhome/lib/core.dataloader/dataloader.js:35
        return super.loadMany(_this._trackedKeys);
               ^^^^^
SyntaxError: 'super' keyword unexpected here
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/briskhome/lib/core.dataloader/index.js:3:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at resolveModuleSync (/opt/briskhome/node_modules/architect/architect.js:117:22)
    at /opt/briskhome/node_modules/architect/architect.js:48:32
    at Array.forEach (native)
    at resolveConfigSync (/opt/briskhome/node_modules/architect/architect.js:41:16)
    at Object.resolveConfig (/opt/briskhome/node_modules/architect/architect.js:35:20)
✨  Done in 1.03s.
```

**Comment by heuels** [comment]
So the problem is that right [here](https://github.com/briskhome/briskhome/blob/develop/src/utilities/architect.js#L146) when architect is trying to require a plugin an error is silently swallowed and it all snowballs up to `core.js`. I will now add a `try...catch` there.

**Comment by heuels** [comment]
Changed **Babel** plugin from `babel-plugin-transform-es2015-modules-commonjs` to `babel-plugin-transform-inline-imports-commonjs`. Theoretically it does not solve the "why" part of this error appearing but defers it, but we shall see.

**Comment by heuels** [comment]
Another error that was being thrown on an original version of **architect**:
```
{ Error: Cannot find module '../components'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/briskhome/lib/core.graphql/index.js:5:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /opt/briskhome/lib/utilities/architect.js:181:25
    at Array.map (native)
    at /opt/briskhome/lib/utilities/architect.js:179:8
    at Generator.next (<anonymous>)
    at step (/opt/briskhome/lib/utilities/architect.js:28:191)
    at /opt/briskhome/lib/utilities/architect.js:28:361
    at process._tickCallback (internal/process/next_tick.js:109:7) code: 'MODULE_NOT_FOUND' }
```

This is clearly linked to rebase side effects in **core.graphql** plugin, but fixing that line somewhy didn't help. Need to investigate this issue further and probably file some new bugs related to **utilities/architect**.

**Comment by heuels** [comment]
Fixed. The problem was that **dataloader** module was not installed.

**Comment by heuels** [comment]
Fixed it. This is the new `.babelrc`:
```
{
  "presets": ["flow", "react"],
  "plugins": [
    "transform-inline-imports-commonjs", 
    "transform-object-rest-spread",
    ["module-resolver", { "root": ["./src"] }]
  ]
}
```
